### ISSUE TITLE
TODO to finalize

### ISSUE THREAD

**Issue by HSGamer** [etases/EduBlock.RS#29]
- [x] Update Student (Staff)
- [x] Get student from id
- [x] Get student list of classroom
- [x] Add students to classroom
- [x] Remove students from classroom
- [x] Add teachers to classroom
- [x] Remove teachers from classroom
