### ISSUE TITLE
Classification

### ISSUE THREAD

**Issue by HSGamer** [etases/EduBlock.RS#35]
# Description
An endpoint to return the latest classification of a record

# Tasks
* [x] Customized equations to calculate classification
* [x] Endpoints
  * [x] Return classification of a record
  * [x] Analyze student classification grouped by grade

# Note
* Use [EvalEx](https://github.com/ezylang/EvalEx) for the equations
