### ISSUE TITLE
Restore Records From StudentUpdater

### ISSUE THREAD

**Issue by HSGamer** [etases/EduBlock.RS#40]
# Description
Add a command to restore student records 

# Tasks
* [x] Add support to set id on database entities manually
* [ ] Get all student personal & record
* [x] Restore data from StudentUpdater to Database

# Note
